
title = "02 Mengenbeweise, Relationen, Abbildungen"                      # the file name of the output pdf
description = "Mengenbeweise, Relationen und Abbildungen"                #
content = ["mengenbeweise","relationen", "abbildungen"]
xkcd = 1445
