title = "09 Homomorphismen, Huffman Bäume, Grammatiken"                  # the file name of the output pdf
description = "Homomorphismen, Huffman Bäume und Grammatiken"  # 
content = ["homomorphismen", "huffman", "grammatiken"]
xkcd = 1738
