
title = "03 Aussagenlogik, Alphabete, Woerter"          # the file name of the output pdf
description = "03 Aussagenlogik, Alphabete und Woerter" # 
content = ["aussagenlogik", "beweisbarkeit", "woerter"]
xkcd = 704
