
title = "01 Orga, Mengenlehre, Relationen"                             # the file name of the output pdf
description = "Orga, Mengenlehre und Relationen"                       # 
content = ["orga", "mengenlehre", "kartesischesprodukt", "relationen"]
xkcd = 934
